{
    "fId":53,
    "shiftDate":"2020-07-30",
    "shift":"AM",
    "placement":1,
    "cashier":1,
    "pumpAttendants":[
       2,
       3
    ],
    "group1":{
       "accelrate":0.03,
       "diesel":0.03,
       "jxpremium":3.3
    },
    "group2":{
       "accelrate":33.12,
       "diesel":0.03,
       "jxpremium":0.03
    },
    "pump1":{
       "accelrate":{
          "beg":0.003,
          "end":0.003,
          "cal":0.3,
          "mgn":0.3,
          "advRd":0.03
       },
       "diesel":{
          "beg":0.003,
          "end":0.003,
          "cal":0.3,
          "mgn":0.3,
          "advRd":0.03
       },
       "jxpremium":{
          "beg":0.003,
          "end":0.003,
          "cal":0.3,
          "mgn":0.3,
          "advRd":0.03
       }
    },
    "pump2":{
       "accelrate":{
          "beg":0.003,
          "end":0.003,
          "cal":0.3,
          "mgn":0.3,
          "advRd":0.03
       },
       "diesel":{
          "beg":0.003,
          "end":0.003,
          "cal":0.3,
          "mgn":0.3,
          "advRd":0.03
       },
       "jxpremium":{
          "beg":0.003,
          "end":0.003,
          "cal":0.3,
          "mgn":0.3,
          "advRd":0.03
       }
    },
    "pump3":{
       "accelrate":{
          "beg":0.003,
          "end":0.003,
          "cal":0.3,
          "mgn":0.3,
          "advRd":0.03
       },
       "diesel":{
          "beg":0.003,
          "end":0.003,
          "cal":0.3,
          "mgn":0.3,
          "advRd":0.03
       },
       "jxpremium":{
          "beg":0.003,
          "end":0.003,
          "cal":0.3,
          "mgn":0.3,
          "advRd":0.03
       }
    },
    "pump4":{
       "accelrate":{
          "beg":0.003,
          "end":0.003,
          "cal":0.3,
          "mgn":0.3,
          "advRd":0.03
       },
       "diesel":{
          "beg":0.003,
          "end":0.003,
          "cal":0.3,
          "mgn":0.3,
          "advRd":0.03
       },
       "jxpremium":{
          "beg":0.003,
          "end":0.003,
          "cal":0.3,
          "mgn":0.3,
          "advRd":0.03
       }
    },
    "dropForm":{
       "drops":33,
       "amtPerDrop":0.03,
       "lastDrop":30.03
    },
    "breakdown":{
       "fId":53,
       "count1000":0,
       "count500":0,
       "count200":0,
       "count100":0,
       "count50":0,
       "count20":0,
       "count10":0,
       "count5":0,
       "count1":3,
       "count025":0
    },
    "expenses":[
 
    ],
    "creditsales":[
 
    ],
    "cashadvance":[
 
    ],
    "diesel":{
       "closingLevel":3,
       "closingLiters":3,
       "openingLevel":0,
       "openingLiters":0
    },
    "accelrate":{
       "closingLevel":3,
       "closingLiters":3,
       "openingLevel":0,
       "openingLiters":0
    },
    "jxpremium":{
       "closingLevel":3,
       "closingLiters":3,
       "openingLevel":0,
       "openingLiters":0
    }
 }